import eslint from '@eslint/js'
import tseslint from 'typescript-eslint'
import eslintReactKit from '@eslint-react/kit'
import { jsxNoLiterals } from './eslint/jsx-no-literals.mjs'

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    ignores: ['dist/**', 'node_modules/**', 'e2e/**', 'src/server/lsp/__fixtures__/**'],
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-empty-function': 'off',
      'no-console': ['error', { allow: ['warn', 'error'] }],
      'no-useless-assignment': 'error',
      'no-useless-catch': 'error',
      'no-unsafe-finally': 'error',
      'require-yield': 'error',
      'prefer-const': 'error',
      'no-useless-escape': 'error',
      'preserve-caught-error': 'off',
    },
  },
  // CLI files legitimately use console.log for user-facing output; so do the
  // standalone maintenance scripts (scripts/optimize-snapshots.ts, ...).
  {
    files: ['src/cli/**/*.ts', 'scripts/**/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },
  // Test files have looser rules
  {
    files: ['src/**/*.test.ts', 'web/src/**/*.test.ts', 'web/src/**/*.test.tsx'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-useless-assignment': 'off',
      'no-console': 'off',
      'require-yield': 'off',
      'prefer-const': 'off',
    },
  },
  // i18n gate: no raw user-facing strings in JSX (en + fr mandatory).
  // Strict for JSX text content; only a curated set of user-facing attributes
  // is checked (aria-label, placeholder, title, alt). Styling/semantic
  // attributes (className, type, src, ...) are intentionally left alone.
  {
    ...eslintReactKit()
      .use(jsxNoLiterals, {
        noStrings: true,
        restrictedAttributes: ['aria-label', 'placeholder', 'title', 'alt'],
        // Standalone symbols/emoji used as decorative JSX text and the brand
        // name / typographic quotes — not translatable.
        allowedStrings: [
          '·',
          '✓',
          '○',
          '/',
          '...',
          '🔍',
          '☆',
          '★',
          '*',
          '✕',
          '✎',
          '✗',
          '$',
          '📍',
          '⚠️',
          '●',
          '└',
          '↻',
          '|',
          '+',
          '#',
          'OpenFox',
          'OpenAI',
          'GitHub',
          '/home/user/projects',
          'feature/my-branch',
          'npm run dev',
          'http://localhost:3000',
          'http://proxy:8080',
          'vscode://',
          '/path/to/file',
          'vscode-remote/ssh-remote+username@192.168.1.100',
          'vscode://vscode-remote/ssh-remote+username@192.168.1.100/path/to/file',
          'http://localhost:4000',
          'https://github.com/user/repo',
          'my-plugin',
          '“',
          '”',
          '(',
          ')',
          '[',
          ']',
          ':',
          ';',
          ',',
          '.',
          '!',
          '?',
          '—',
          '–',
          '⋮',
          'original',
          'workspace name',
          '▶',
          '▼',
          '⏳',
          'pp',
          'tg',
          ' - ',
          'PP t/s',
          'TG t/s',
          '×',
          'Stdio',
          'HTTP',
          'e.g. npx',
          'API_KEY=xxx',
          'X-API-Key=xxx',
          'e.g. https://mcp.example.com/mcp',
          'tvly-...',
          'e.g. filesystem',
          'tavily.com',
          'README',
          'MCP Servers',
          'http://localhost:8000',
          'sk-...',
          'model-name',
          '↑',
          '↓',
          '←',
          'npm install --prefer-offline',
          '/absolute/or/relative/path',
          '▲',
          'e.g. success, passed, failed',
          'e.g. criteria, todos, review_findings',
          'e.g. status',
          'e.g. passed, resolved',
          'e.g. resolved, dismissed',
          'cd {{workdir}} && npm run lint',
          'e.g. build, verify, review',
          'e.g. build, verify',
          'my_agent',
          '−',
          '↩︎',
          'my-skill',
          '1.0.0',
          'http://localhost:11434',
          'http://localhost:8000/v1',
          'qwen3.5:0.8b',
          'qwen3.5-27b',
          '99+',
          'MCP',
          'ASAP',
          '-',
          'v',
          '>',
          '…',
        ],
        // Terminal commands and paths rendered verbatim in <code> stay English.
        elementOverrides: { code: { allowElement: true } },
      })
      .getConfig(),
    files: ['web/src/**/*.{ts,tsx}'],
    name: 'openfox/i18n/jsx-no-literals',
  },
  // i18n gate does not apply to test files (they assert English strings)
  {
    files: ['web/src/**/*.test.ts', 'web/src/**/*.test.tsx'],
    rules: {
      '@eslint-react/kit/jsx-no-literals': 'off',
    },
  },
)
